command:
  - "gunicorn"
  - "backend.main:app"
  - "-w"
  - "2"
  - "-b"
  - "127.0.0.1:8000"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "app-warehouse"
  - name: DATABRICKS_CATALOG
    value: main
  - name: DATABRICKS_SCHEMA
    value: default
  - name: DATABRICKS_VOLUME_NAME
    value: nametags
  - name: DATABRICKS_VOLUME_PATH
    valueFrom: "app-volume"
  - name: PORT
    value: "8000"
  - name: ALLOW_EMAIL_REUSE
    value: "true"
